# Сборка Docker-образа и запуск контейнера
build:
    docker-compose up --build

# Остановка и удаление контейнера
clean:
    docker-compose down

# Удаление всех остановленных контейнеров
prune:
    docker container prune -f

