name: CI Tests

on: [push, pull_request]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: ${{ github.workspace }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y make gcc
        sudo apt-get install -y qemu-system-x86 qemu-system-gui qemu-utils

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install "pytest<8.0.0" pytest-cov  # Для совместимости с pytest-cov

    - name: Configure git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git config --global init.defaultBranch main

    - name: Verify installations
      run: |
        make --version
        gcc --version
        qemu-system-x86_64 --version

    - name: Debug info
      run: |
        ls -lR lab_ready || echo "lab_ready not found"
        which qemu-system-x86_64 || echo "QEMU not found!"

    - name: Run tests
      run: |
        pytest --cov=scripts --cov-report=xml -v tests/functional/ tests/integration/

    - name: Upload coverage
      uses: codecov/codecov-action@v3
